In [1]:
import numpy as np
import ia870 as mm
from PIL import Image
import ia636 as iashow

In [2]:
a = mm.iatext('a')
b = mm.iaframe(a)

Image.fromarray(a.astype(np.uint8)*255)

In [3]:
Image.fromarray(b.astype(np.uint8)*255)

In [4]:
print 'a=\n',a *1
print 'b=\n',b *1

a=
[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 1 1 1 1 1 0 0]
 [0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1 0]
 [0 0 1 1 1 1 1 1 0]
 [0 1 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 1 1 0]
 [0 0 1 1 1 1 0 1 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]
b=
[[1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1]]


In [14]:
from ia870 import iaero
from ia870 import iabinary


f=iabinary([
    [1, 1, 1, 0, 0, 1, 1],
    [1, 0, 1, 1, 1, 0, 0],
    [0, 0, 0, 0, 1, 0, 0]])
b=iabinary([1, 1, 0])
iaero(f,b)

array([[ True,  True,  True, False, False, False,  True],
       [ True, False, False,  True,  True, False, False],
       [False, False, False, False, False, False, False]], dtype=bool)

In [15]:
Image.fromarray(f.astype(np.uint8)*255)

In [16]:
f = np.array([
    [ 0,   1,  2, 50,  4,  5],
    [ 2,   3,  4,  0,  0,  0],
    [12, 255, 14, 15, 16, 17]], dtype=np.uint8)
iaero(f,b)

array([[ 0,  0,  1,  2,  4,  4],
       [ 2,  2,  3,  0,  0,  0],
       [12, 12, 14, 14, 15, 16]], dtype=uint8)

In [17]:
Image.fromarray(f.astype(np.uint8)*255)